/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontFam2 = 'MyFlutterApp2';
  static const _kFontFam3 = 'MyFlutterApp3';
  static const String? _kFontPkg = null;

  static const IconData doc_text =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poll_h =
      IconData(0xf682, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll =
      IconData(0xf70e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up =
      IconData(0xe800, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData thumbs_down =
      IconData(0xe801, fontFamily: _kFontFam2, fontPackage: _kFontPkg);

  static const IconData clapping_svgrepo_com =
      IconData(0xe800, fontFamily: _kFontFam3, fontPackage: _kFontPkg);
  static const IconData muscle_svgrepo_com__1_ =
      IconData(0xe802, fontFamily: _kFontFam3, fontPackage: _kFontPkg);
}
